# Generated by Django 4.1.2 on 2022-10-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='resim',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
