# Generated by Django 4.1.2 on 2022-10-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0004_hepsiburada'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='link1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='link2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='link3',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
