# Generated by Django 4.1.2 on 2022-10-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0005_notebook_link1_notebook_link2_notebook_link3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='link2',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='link3',
        ),
    ]
