# Generated by Django 4.1.2 on 2022-10-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0006_remove_notebook_link2_remove_notebook_link3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hepsiburada',
            name='model',
        ),
    ]
