# Generated by Django 4.1.2 on 2022-10-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0007_remove_hepsiburada_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='link1',
        ),
    ]
